name: hacker_news
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0"

dependencies:
  moor_flutter: ^1.4.0
  url_launcher: ^5.0.2

  built_collection: ^4.2.2
  built_value: ^6.5.0

  http: ^0.12.0+2

  rxdart: ^0.18.1

  font_awesome_flutter: ^8.4.0

  webview_flutter: ^0.3.7+1

  provider: ^2.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.2+1

dev_dependencies:
  build_runner: ^1.4.0
  built_value_generator: ^6.5.0
  moor_generator: ^1.4.0

  test: ^1.6.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: PressStart
      fonts:
        - asset: fonts/PressStart2P-Regular.ttf

